### PR TITLE
fix: destroy stream on error

### LINKED ISSUE #41: test out in conjunction with remix-auth
https://discord.com/channels/770287896669978684/770287896669978687/1026625568751489034

### LINKED ISSUE #491: Handle stream error in `responseToReadable`
One of my Remix routes returns a stream response, but when running through `remix-fastify`, errors occurring during the stream aren't being properly caught, leading to unhandled promise errors.

After digging into the source code, I found this related `responseToReadable`:

https://github.com/mcansh/remix-fastify/blob/74abcef4c1a74b055c8c7fac4902055a77db76e4/packages/remix-fastify/src/shared.ts#L124-L139

In this function, `await reader.read()` will throw if the stream has errors, but it's not catched.

Suggested fix: catch this error and call `readable.destroy(error)`

### PR DESCRIPTION
**Pull request by mcansh**
fixes #491

Co-Authored-By: wong2 <wonderfuly@gmail.com>

### CODE REVIEW

File: packages/remix-fastify/src/shared.ts [hunk 1]
```diff
@@ -126,14 +126,20 @@ function responseToReadable(response: Response): Readable | null {
...
+      } else {
+        readable.push(null);
+      }
+    };
+
+    return readable;
+  } catch (error) {
+    readable.destroy(error);
+    throw error;
+  }
```
Comment (wong2) [inline packages/remix-fastify/src/shared.ts:144]: This won't catch exception thrown from `reader.read()`

Comment (wong2) [reply packages/remix-fastify/src/shared.ts:144]: @mcansh

Comment (wong2) [reply packages/remix-fastify/src/shared.ts:144]: @mcansh Can you fix this?
