### PR TITLE
fix: return reply from response handler

### LINKED ISSUE #99: stream closed prematurely when using @fastify/compress
According to this issue https://github.com/fastify/fastify-compress/issues/215 you need to return `reply`.

Patched the code in my node_modules and it works

### PR DESCRIPTION
**Pull request by danreeves**
Enabling `@fastify/compress` causes responsed to be prematurely closed. e.g.

```ts
await app.register(import("@fastify/compress"), { global: true })
```

This seems related to this fastify v4 migration point: https://www.fastify.io/docs/latest/Guides/Migration-Guide-V4/#need-to-return-reply-to-signal-a-fork-of-the-promise-chain

(This is the first time I'm using fastify though)

closes #99

### CODE REVIEW

File: packages/remix-fastify/src/server.ts [hunk 1]
```diff
@@ -57,7 +57,7 @@ export function createRequestHandler({
       loadContext
     )) as NodeResponse;
 
-    await sendRemixResponse(reply, response);
+    return await sendRemixResponse(reply, response);
```
Comment (mcansh) [inline packages/remix-fastify/src/server.ts:60]:
```suggestion
    return sendRemixResponse(reply, response);
```

**Review by mcansh — APPROVED** [review]
